# Generated by Django 2.2.6 on 2019-11-04 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, unique=True)),
                ('class_name', models.CharField(max_length=30)),
                ('section_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('age', models.DateField()),
                ('address', models.TextField()),
                ('guardient', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ClassName')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yellow', 'YELLOW'), ('green', 'GREEN'), ('red', 'RED')], default='yellow', max_length=20)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='student.Student')),
            ],
        ),
    ]
