# Generated by Django 2.2.6 on 2019-11-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191105_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
