# Generated by Django 2.2.6 on 2019-11-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191105_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='slug',
            field=models.SlugField(default='defalut', unique=True),
            preserve_default=False,
        ),
    ]
